spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: info
    root: info

jwt:
  header: Authorization
  issuer: ajufresh@gmail.com
  secret_key: myblog!jjD3yHK5DNOjhGcZRNOnQkiAorHepx7GKGYbQfAJ8MM0tMdjH3